### PR TITLE
Order by DeletedAt first when de-duplicating. Update org name data type.

### PR DESCRIPTION
**Pull request by geneh**

### CODE REVIEW

**Comment by kelewis** [comment]
Can things get deleted and then undeleted?  Will a valid row ever arrive with a processedAt that is alter than deletedAt?  If so we may want to change this approach to take the latest date between deletedAt and processedAt then sort/dedupe off of that result.

**Comment by geneh** [comment]
As far as I know, things cannot be undeleted. For example, if a repo is deleted and then created with the same name, the id's will be different, so technically it would be a different repo.
DeletedAt will either be null or later than ProcessedAt date.
Does it make sense?

**Comment by kelewis** [comment]
Yep.  Sounds good then.

**Comment by geneh** [comment]
Thanks!

**Pull request merged**
